# Generated by Django 5.1.1 on 2024-11-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keypair', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keypair',
            name='type',
            field=models.CharField(choices=[('DSA', 'DSA'), ('RSA', 'RSA'), ('ECDSA', 'ECDSA'), ('EdDSA', 'EdDSA')], default='RSA', max_length=10),
            preserve_default=False,
        ),
    ]
