# Generated by Django 5.1.1 on 2024-10-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='img_path',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
