# Generated by Django 5.1.1 on 2024-11-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='img_path',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
