# Generated by Django 5.1.1 on 2024-10-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_alter_picture_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='img_path',
            field=models.CharField(max_length=255),
        ),
    ]
